-- =====================================================================
--  MINI ERP - Sistema de Gestion Comercial
--  Migracion V1 : Esquema relacional inicial
--  Motor      : PostgreSQL 18.x (compatible desde 12+)
--  Metodo de valuacion de inventario: UEPS (LIFO)
-- =====================================================================
--  Convenciones:
--    - Nomenclatura en snake_case y en espanol (lenguaje del dominio).
--    - Llaves primarias BIGINT GENERATED BY DEFAULT AS IDENTITY, para
--      permitir la carga inicial con identificadores explicitos y a la
--      vez delegar la generacion a la base en tiempo de ejecucion.
--    - Los catalogos usan borrado logico (columna "activo"), nunca
--      borrado fisico, para preservar el historico de operaciones.
--    - Las restricciones CHECK implementan las reglas del negocio a
--      nivel de motor, como segunda linea de defensa frente a la capa
--      de servicios del backend.
-- =====================================================================


-- =====================================================================
--  1. SEGURIDAD Y CONTROL DE ACCESO
-- =====================================================================

-- ---------------------------------------------------------------------
--  Tabla: rol
--  Las cuatro areas funcionales descritas en el enunciado. Se modela
--  como catalogo y no como ENUM nativo para permitir su consulta,
--  documentacion y eventual ampliacion sin alterar tipos del motor.
-- ---------------------------------------------------------------------
CREATE TABLE rol (
    id_rol      SMALLINT      GENERATED BY DEFAULT AS IDENTITY,
    nombre      VARCHAR(30)   NOT NULL,
    descripcion VARCHAR(200)  NOT NULL,

    CONSTRAINT pk_rol        PRIMARY KEY (id_rol),
    CONSTRAINT uq_rol_nombre UNIQUE (nombre),
    CONSTRAINT ck_rol_nombre CHECK (nombre IN ('ADMINISTRACION','COMPRAS','INVENTARIO','VENTAS'))
);

COMMENT ON TABLE  rol IS 'Areas funcionales del sistema. Determina los permisos de cada usuario.';


-- ---------------------------------------------------------------------
--  Tabla: usuario
--  Cada empleado accede con credenciales propias. La contrasena se
--  almacena unicamente como hash BCrypt (60 caracteres).
-- ---------------------------------------------------------------------
CREATE TABLE usuario (
    id_usuario      BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    nombre_usuario  VARCHAR(40)   NOT NULL,
    contrasena      VARCHAR(100)  NOT NULL,
    nombre_completo VARCHAR(120)  NOT NULL,
    correo          VARCHAR(120)  NOT NULL,
    id_rol          SMALLINT      NOT NULL,
    activo          BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ultimo_acceso   TIMESTAMP,

    CONSTRAINT pk_usuario         PRIMARY KEY (id_usuario),
    CONSTRAINT uq_usuario_nombre  UNIQUE (nombre_usuario),
    CONSTRAINT uq_usuario_correo  UNIQUE (correo),
    CONSTRAINT fk_usuario_rol     FOREIGN KEY (id_rol) REFERENCES rol (id_rol),
    CONSTRAINT ck_usuario_correo  CHECK (correo LIKE '%_@_%._%'),
    CONSTRAINT ck_usuario_nombre  CHECK (LENGTH(TRIM(nombre_usuario)) >= 4)
);

CREATE INDEX ix_usuario_rol ON usuario (id_rol);

COMMENT ON COLUMN usuario.contrasena IS 'Hash BCrypt. Nunca se almacena la contrasena en texto plano.';


-- =====================================================================
--  2. CATALOGO DE PRODUCTOS
-- =====================================================================

-- ---------------------------------------------------------------------
--  Tabla: categoria
--  Clasificacion comercial de los productos (enunciado: "debidamente
--  identificados y clasificados").
-- ---------------------------------------------------------------------
CREATE TABLE categoria (
    id_categoria BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    nombre       VARCHAR(60)  NOT NULL,
    descripcion  VARCHAR(200),
    activo       BOOLEAN      NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_categoria        PRIMARY KEY (id_categoria),
    CONSTRAINT uq_categoria_nombre UNIQUE (nombre)
);


-- ---------------------------------------------------------------------
--  Tabla: producto
--
--  "stock_actual" es una columna derivada que se mantiene de forma
--  transaccional junto con el kardex. Se almacena (y no se calcula en
--  cada consulta) por dos motivos:
--    a) permite imponer la regla "no existencias negativas" mediante un
--       CHECK a nivel de motor, imposible sobre una columna calculada;
--    b) evita agregaciones sobre todo el historico en cada validacion
--       de venta.
--  La vista vw_existencia_calculada reconcilia esta columna contra la
--  suma real de movimientos del kardex.
-- ---------------------------------------------------------------------
CREATE TABLE producto (
    id_producto    BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    codigo         VARCHAR(20)   NOT NULL,
    nombre         VARCHAR(120)  NOT NULL,
    descripcion    VARCHAR(300),
    id_categoria   BIGINT        NOT NULL,
    unidad_medida  VARCHAR(20)   NOT NULL DEFAULT 'UNIDAD',
    precio_venta   NUMERIC(12,2) NOT NULL,
    stock_actual   INTEGER       NOT NULL DEFAULT 0,
    stock_minimo   INTEGER       NOT NULL DEFAULT 0,
    activo         BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_producto            PRIMARY KEY (id_producto),
    CONSTRAINT uq_producto_codigo     UNIQUE (codigo),
    CONSTRAINT fk_producto_categoria  FOREIGN KEY (id_categoria) REFERENCES categoria (id_categoria),
    CONSTRAINT ck_producto_precio     CHECK (precio_venta > 0),
    CONSTRAINT ck_producto_stock      CHECK (stock_actual >= 0),
    CONSTRAINT ck_producto_stock_min  CHECK (stock_minimo >= 0)
);

CREATE INDEX ix_producto_categoria ON producto (id_categoria);
CREATE INDEX ix_producto_activo    ON producto (activo) WHERE activo = TRUE;
CREATE INDEX ix_producto_nombre    ON producto (LOWER(nombre));

COMMENT ON CONSTRAINT ck_producto_stock ON producto
    IS 'Regla del negocio: no se permiten operaciones que provoquen existencias negativas.';


-- =====================================================================
--  3. PROVEEDORES Y COMPRAS
-- =====================================================================

CREATE TABLE proveedor (
    id_proveedor   BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    nit            VARCHAR(20)   NOT NULL,
    nombre         VARCHAR(120)  NOT NULL,
    contacto       VARCHAR(120),
    telefono       VARCHAR(20),
    correo         VARCHAR(120),
    direccion      VARCHAR(200),
    activo         BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_proveedor     PRIMARY KEY (id_proveedor),
    CONSTRAINT uq_proveedor_nit UNIQUE (nit)
);


-- ---------------------------------------------------------------------
--  Tabla: proveedor_producto
--  Relacion muchos-a-muchos exigida por el enunciado: "Un proveedor
--  podra suministrar diferentes productos y un mismo producto podra ser
--  adquirido a diferentes proveedores".
-- ---------------------------------------------------------------------
CREATE TABLE proveedor_producto (
    id_proveedor     BIGINT        NOT NULL,
    id_producto      BIGINT        NOT NULL,
    costo_referencia NUMERIC(12,2) NOT NULL,
    fecha_asociacion TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_proveedor_producto PRIMARY KEY (id_proveedor, id_producto),
    CONSTRAINT fk_pp_proveedor       FOREIGN KEY (id_proveedor) REFERENCES proveedor (id_proveedor),
    CONSTRAINT fk_pp_producto        FOREIGN KEY (id_producto)  REFERENCES producto (id_producto),
    CONSTRAINT ck_pp_costo           CHECK (costo_referencia > 0)
);

CREATE INDEX ix_pp_producto ON proveedor_producto (id_producto);


-- ---------------------------------------------------------------------
--  Tabla: compra
--  Documento de adquisicion. Conserva "de quien se adquirio" y "cuando
--  se realizo la operacion". El detalle conserva "que se adquirio" y
--  "en que cantidades".
-- ---------------------------------------------------------------------
CREATE TABLE compra (
    id_compra        BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    numero_documento VARCHAR(20)   NOT NULL,
    id_proveedor     BIGINT        NOT NULL,
    id_usuario       BIGINT        NOT NULL,
    fecha_compra     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total            NUMERIC(14,2) NOT NULL DEFAULT 0,
    observaciones    VARCHAR(300),

    CONSTRAINT pk_compra            PRIMARY KEY (id_compra),
    CONSTRAINT uq_compra_documento  UNIQUE (numero_documento),
    CONSTRAINT fk_compra_proveedor  FOREIGN KEY (id_proveedor) REFERENCES proveedor (id_proveedor),
    CONSTRAINT fk_compra_usuario    FOREIGN KEY (id_usuario)   REFERENCES usuario (id_usuario),
    CONSTRAINT ck_compra_total      CHECK (total >= 0)
);

CREATE INDEX ix_compra_proveedor ON compra (id_proveedor);
CREATE INDEX ix_compra_fecha     ON compra (fecha_compra);
CREATE INDEX ix_compra_usuario   ON compra (id_usuario);


-- ---------------------------------------------------------------------
--  Tabla: detalle_compra
--  "costo_unitario" se congela al momento de la operacion: aunque el
--  costo de referencia del proveedor cambie despues, el historico de la
--  compra permanece intacto.
-- ---------------------------------------------------------------------
CREATE TABLE detalle_compra (
    id_detalle_compra BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    id_compra         BIGINT        NOT NULL,
    id_producto       BIGINT        NOT NULL,
    cantidad          INTEGER       NOT NULL,
    costo_unitario    NUMERIC(12,2) NOT NULL,
    subtotal          NUMERIC(14,2) GENERATED ALWAYS AS (cantidad * costo_unitario) STORED,

    CONSTRAINT pk_detalle_compra   PRIMARY KEY (id_detalle_compra),
    CONSTRAINT fk_dc_compra        FOREIGN KEY (id_compra)   REFERENCES compra (id_compra) ON DELETE CASCADE,
    CONSTRAINT fk_dc_producto      FOREIGN KEY (id_producto) REFERENCES producto (id_producto),
    CONSTRAINT uq_dc_compra_prod   UNIQUE (id_compra, id_producto),
    CONSTRAINT ck_dc_cantidad      CHECK (cantidad > 0),
    CONSTRAINT ck_dc_costo         CHECK (costo_unitario > 0)
);

CREATE INDEX ix_dc_producto ON detalle_compra (id_producto);

COMMENT ON COLUMN detalle_compra.subtotal
    IS 'Columna generada por el motor: garantiza que el subtotal siempre concuerde con cantidad * costo_unitario.';


-- =====================================================================
--  4. CLIENTES Y VENTAS
-- =====================================================================

CREATE TABLE cliente (
    id_cliente     BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    nit            VARCHAR(20)   NOT NULL,
    nombre         VARCHAR(120)  NOT NULL,
    telefono       VARCHAR(20),
    correo         VARCHAR(120),
    direccion      VARCHAR(200),
    activo         BOOLEAN       NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_cliente     PRIMARY KEY (id_cliente),
    CONSTRAINT uq_cliente_nit UNIQUE (nit)
);

CREATE INDEX ix_cliente_nombre ON cliente (LOWER(nombre));


-- ---------------------------------------------------------------------
--  Tabla: venta
--  El porcentaje de IVA se almacena en cada venta para que la factura
--  historica conserve la tasa vigente al momento de emitirse, aunque la
--  tasa cambie en el futuro.
-- ---------------------------------------------------------------------
CREATE TABLE venta (
    id_venta       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    numero_factura VARCHAR(20)   NOT NULL,
    id_cliente     BIGINT        NOT NULL,
    id_usuario     BIGINT        NOT NULL,
    fecha_venta    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    subtotal       NUMERIC(14,2) NOT NULL DEFAULT 0,
    porcentaje_iva NUMERIC(5,4)  NOT NULL DEFAULT 0.1200,
    iva            NUMERIC(14,2) NOT NULL DEFAULT 0,
    total          NUMERIC(14,2) NOT NULL DEFAULT 0,

    CONSTRAINT pk_venta           PRIMARY KEY (id_venta),
    CONSTRAINT uq_venta_factura   UNIQUE (numero_factura),
    CONSTRAINT fk_venta_cliente   FOREIGN KEY (id_cliente) REFERENCES cliente (id_cliente),
    CONSTRAINT fk_venta_usuario   FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT ck_venta_subtotal  CHECK (subtotal >= 0),
    CONSTRAINT ck_venta_iva       CHECK (iva >= 0),
    CONSTRAINT ck_venta_pct_iva   CHECK (porcentaje_iva >= 0 AND porcentaje_iva < 1),
    CONSTRAINT ck_venta_total     CHECK (total = subtotal + iva)
);

CREATE INDEX ix_venta_cliente ON venta (id_cliente);
CREATE INDEX ix_venta_fecha   ON venta (fecha_venta);
CREATE INDEX ix_venta_usuario ON venta (id_usuario);

COMMENT ON CONSTRAINT ck_venta_total ON venta
    IS 'El motor garantiza la coherencia aritmetica del documento: total = subtotal + iva.';


-- ---------------------------------------------------------------------
--  Tabla: detalle_venta
--  "precio_unitario" se congela al momento de la venta.
--  "costo_unitario" es el costo promedio ponderado que resulto de
--  consumir las capas de inventario bajo UEPS; permite calcular margen
--  y costo de ventas sin recalcular el kardex.
-- ---------------------------------------------------------------------
CREATE TABLE detalle_venta (
    id_detalle_venta BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    id_venta         BIGINT        NOT NULL,
    id_producto      BIGINT        NOT NULL,
    cantidad         INTEGER       NOT NULL,
    precio_unitario  NUMERIC(12,2) NOT NULL,
    costo_unitario   NUMERIC(14,4) NOT NULL DEFAULT 0,
    subtotal         NUMERIC(14,2) GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,

    CONSTRAINT pk_detalle_venta  PRIMARY KEY (id_detalle_venta),
    CONSTRAINT fk_dv_venta       FOREIGN KEY (id_venta)    REFERENCES venta (id_venta) ON DELETE CASCADE,
    CONSTRAINT fk_dv_producto    FOREIGN KEY (id_producto) REFERENCES producto (id_producto),
    CONSTRAINT uq_dv_venta_prod  UNIQUE (id_venta, id_producto),
    CONSTRAINT ck_dv_cantidad    CHECK (cantidad > 0),
    CONSTRAINT ck_dv_precio      CHECK (precio_unitario > 0),
    CONSTRAINT ck_dv_costo       CHECK (costo_unitario >= 0)
);

CREATE INDEX ix_dv_producto ON detalle_venta (id_producto);


-- =====================================================================
--  5. INVENTARIO : CAPAS DE COSTO (UEPS) Y KARDEX
-- =====================================================================

-- ---------------------------------------------------------------------
--  Tabla: capa_inventario
--
--  Nucleo del metodo de valuacion. Cada linea de compra crea una capa
--  con su propio costo unitario. Las salidas consumen capas en orden
--  UEPS (ultima entrada disponible primero), decrementando
--  cantidad_disponible. Una capa agotada permanece en la tabla como
--  parte del historico.
--
--  El indice parcial ix_capa_ueps ordena exactamente como las necesita
--  el algoritmo, de modo que la seleccion de capas sea una lectura
--  secuencial del indice y no una ordenacion en memoria.
-- ---------------------------------------------------------------------
CREATE TABLE capa_inventario (
    id_capa             BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    id_producto         BIGINT        NOT NULL,
    id_detalle_compra   BIGINT        NOT NULL,
    fecha_entrada       TIMESTAMP     NOT NULL,
    costo_unitario      NUMERIC(14,4) NOT NULL,
    cantidad_inicial    INTEGER       NOT NULL,
    cantidad_disponible INTEGER       NOT NULL,

    CONSTRAINT pk_capa             PRIMARY KEY (id_capa),
    CONSTRAINT fk_capa_producto    FOREIGN KEY (id_producto)       REFERENCES producto (id_producto),
    CONSTRAINT fk_capa_detalle     FOREIGN KEY (id_detalle_compra) REFERENCES detalle_compra (id_detalle_compra) ON DELETE CASCADE,
    CONSTRAINT uq_capa_detalle     UNIQUE (id_detalle_compra),
    CONSTRAINT ck_capa_inicial     CHECK (cantidad_inicial > 0),
    CONSTRAINT ck_capa_costo       CHECK (costo_unitario > 0),
    CONSTRAINT ck_capa_disponible  CHECK (cantidad_disponible >= 0 AND cantidad_disponible <= cantidad_inicial)
);

CREATE INDEX ix_capa_ueps ON capa_inventario (id_producto, fecha_entrada DESC, id_capa DESC)
    WHERE cantidad_disponible > 0;

COMMENT ON TABLE capa_inventario
    IS 'Capas de costo para valuacion UEPS. Cada linea de compra genera una capa independiente.';


-- ---------------------------------------------------------------------
--  Tabla: consumo_capa
--  Trazabilidad completa: que capa de costo alimento que linea de
--  venta y en que cantidad. Permite auditar el costo de ventas capa por
--  capa y reconstruir el calculo UEPS de cualquier venta historica.
-- ---------------------------------------------------------------------
CREATE TABLE consumo_capa (
    id_consumo       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    id_capa          BIGINT        NOT NULL,
    id_detalle_venta BIGINT        NOT NULL,
    cantidad         INTEGER       NOT NULL,
    costo_unitario   NUMERIC(14,4) NOT NULL,
    costo_total      NUMERIC(16,4) GENERATED ALWAYS AS (cantidad * costo_unitario) STORED,

    CONSTRAINT pk_consumo        PRIMARY KEY (id_consumo),
    CONSTRAINT fk_consumo_capa   FOREIGN KEY (id_capa)          REFERENCES capa_inventario (id_capa),
    CONSTRAINT fk_consumo_dv     FOREIGN KEY (id_detalle_venta) REFERENCES detalle_venta (id_detalle_venta) ON DELETE CASCADE,
    CONSTRAINT uq_consumo        UNIQUE (id_capa, id_detalle_venta),
    CONSTRAINT ck_consumo_cant   CHECK (cantidad > 0),
    CONSTRAINT ck_consumo_costo  CHECK (costo_unitario > 0)
);

CREATE INDEX ix_consumo_dv ON consumo_capa (id_detalle_venta);


-- ---------------------------------------------------------------------
--  Tabla: movimiento_inventario  (KARDEX)
--
--  Responde a la exigencia del enunciado: "ademas de conocer la
--  existencia actual, debera ser posible determinar como y por que se
--  han producido cambios en las cantidades disponibles de un producto".
--
--    - tipo_movimiento : que efecto tuvo (ENTRADA / SALIDA)
--    - origen          : por que ocurrio (COMPRA / VENTA / AJUSTE)
--    - id_compra / id_venta : el documento que lo respalda
--
--  En lugar de una referencia polimorfica (un unico id_documento con
--  un discriminador, que rompe la integridad referencial), se usan dos
--  llaves foraneas excluyentes validadas por ck_mov_documento. Asi el
--  motor garantiza que todo movimiento de compra apunte realmente a una
--  compra existente y todo movimiento de venta a una venta existente.
-- ---------------------------------------------------------------------
CREATE TABLE movimiento_inventario (
    id_movimiento       BIGINT        GENERATED BY DEFAULT AS IDENTITY,
    id_producto         BIGINT        NOT NULL,
    tipo_movimiento     VARCHAR(10)   NOT NULL,
    origen              VARCHAR(20)   NOT NULL,
    cantidad            INTEGER       NOT NULL,
    costo_unitario      NUMERIC(14,4) NOT NULL DEFAULT 0,
    existencia_anterior INTEGER       NOT NULL,
    existencia_nueva    INTEGER       NOT NULL,
    id_compra           BIGINT,
    id_venta            BIGINT,
    id_usuario          BIGINT        NOT NULL,
    fecha_movimiento    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    observaciones       VARCHAR(300),

    CONSTRAINT pk_movimiento      PRIMARY KEY (id_movimiento),
    CONSTRAINT fk_mov_producto    FOREIGN KEY (id_producto) REFERENCES producto (id_producto),
    CONSTRAINT fk_mov_compra      FOREIGN KEY (id_compra)   REFERENCES compra (id_compra) ON DELETE CASCADE,
    CONSTRAINT fk_mov_venta       FOREIGN KEY (id_venta)    REFERENCES venta (id_venta) ON DELETE CASCADE,
    CONSTRAINT fk_mov_usuario     FOREIGN KEY (id_usuario)  REFERENCES usuario (id_usuario),

    CONSTRAINT ck_mov_tipo        CHECK (tipo_movimiento IN ('ENTRADA','SALIDA')),
    CONSTRAINT ck_mov_origen      CHECK (origen IN ('COMPRA','VENTA','AJUSTE_ENTRADA','AJUSTE_SALIDA')),
    CONSTRAINT ck_mov_cantidad    CHECK (cantidad > 0),
    CONSTRAINT ck_mov_costo       CHECK (costo_unitario >= 0),
    CONSTRAINT ck_mov_existencias CHECK (existencia_anterior >= 0 AND existencia_nueva >= 0),

    -- Coherencia entre el origen del movimiento y su documento de respaldo
    CONSTRAINT ck_mov_documento CHECK (
           (origen = 'COMPRA' AND tipo_movimiento = 'ENTRADA' AND id_compra IS NOT NULL AND id_venta IS NULL)
        OR (origen = 'VENTA'  AND tipo_movimiento = 'SALIDA'  AND id_venta  IS NOT NULL AND id_compra IS NULL)
        OR (origen = 'AJUSTE_ENTRADA' AND tipo_movimiento = 'ENTRADA' AND id_compra IS NULL AND id_venta IS NULL)
        OR (origen = 'AJUSTE_SALIDA'  AND tipo_movimiento = 'SALIDA'  AND id_compra IS NULL AND id_venta IS NULL)
    ),

    -- Coherencia aritmetica: el kardex no puede contradecirse a si mismo
    CONSTRAINT ck_mov_aritmetica CHECK (
           (tipo_movimiento = 'ENTRADA' AND existencia_nueva = existencia_anterior + cantidad)
        OR (tipo_movimiento = 'SALIDA'  AND existencia_nueva = existencia_anterior - cantidad)
    )
);

CREATE INDEX ix_mov_producto_fecha ON movimiento_inventario (id_producto, fecha_movimiento);
CREATE INDEX ix_mov_fecha          ON movimiento_inventario (fecha_movimiento);
CREATE INDEX ix_mov_origen         ON movimiento_inventario (origen);

COMMENT ON CONSTRAINT ck_mov_aritmetica ON movimiento_inventario
    IS 'Impide registrar un movimiento cuyo saldo resultante no corresponda al saldo anterior mas/menos la cantidad.';


-- =====================================================================
--  6. BITACORA DE AUDITORIA
-- =====================================================================

-- ---------------------------------------------------------------------
--  Tabla: bitacora
--  Respalda el "Reporte de logs": principales interacciones de los
--  usuarios dentro de los modulos del sistema.
--
--  "nombre_usuario" se guarda como copia textual ademas de la llave
--  foranea: si un usuario se desactiva o se renombra, la bitacora
--  historica conserva quien realizo la accion en su momento. La FK es
--  nullable para poder registrar intentos de acceso fallidos con
--  usuarios inexistentes.
-- ---------------------------------------------------------------------
CREATE TABLE bitacora (
    id_bitacora      BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    id_usuario       BIGINT,
    nombre_usuario   VARCHAR(40)  NOT NULL,
    modulo           VARCHAR(30)  NOT NULL,
    accion           VARCHAR(30)  NOT NULL,
    entidad_afectada VARCHAR(60),
    id_entidad       BIGINT,
    descripcion      VARCHAR(400) NOT NULL,
    direccion_ip     VARCHAR(45),
    exitoso          BOOLEAN      NOT NULL DEFAULT TRUE,
    fecha_hora       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_bitacora      PRIMARY KEY (id_bitacora),
    CONSTRAINT fk_bitacora_user FOREIGN KEY (id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT ck_bitacora_mod  CHECK (modulo IN ('AUTENTICACION','USUARIOS','CATEGORIAS','PRODUCTOS',
                                                  'PROVEEDORES','COMPRAS','INVENTARIO','CLIENTES',
                                                  'VENTAS','REPORTES')),
    CONSTRAINT ck_bitacora_acc  CHECK (accion IN ('LOGIN','LOGOUT','LOGIN_FALLIDO','CREAR','ACTUALIZAR',
                                                  'DESACTIVAR','ACTIVAR','CONSULTAR','EXPORTAR','ANULAR'))
);

CREATE INDEX ix_bitacora_fecha   ON bitacora (fecha_hora);
CREATE INDEX ix_bitacora_usuario ON bitacora (id_usuario);
CREATE INDEX ix_bitacora_modulo  ON bitacora (modulo);


-- =====================================================================
--  7. VISTAS DE APOYO
-- =====================================================================

-- ---------------------------------------------------------------------
--  vw_alerta_stock
--  "El sistema debera contemplar situaciones en las que las existencias
--   de determinados productos alcancen niveles que requieran atencion".
-- ---------------------------------------------------------------------
CREATE VIEW vw_alerta_stock AS
SELECT p.id_producto,
       p.codigo,
       p.nombre,
       c.nombre AS categoria,
       p.stock_actual,
       p.stock_minimo,
       (p.stock_minimo - p.stock_actual) AS faltante,
       CASE WHEN p.stock_actual = 0          THEN 'SIN_EXISTENCIA'
            WHEN p.stock_actual < p.stock_minimo THEN 'CRITICO'
            ELSE 'EN_MINIMO'
       END AS nivel_alerta
FROM   producto  p
JOIN   categoria c ON c.id_categoria = p.id_categoria
WHERE  p.activo = TRUE
  AND  p.stock_actual <= p.stock_minimo;


-- ---------------------------------------------------------------------
--  vw_existencia_calculada
--  Reconciliacion: recalcula la existencia de cada producto a partir
--  del kardex y la compara contra producto.stock_actual. En un sistema
--  consistente la columna "diferencia" debe ser siempre 0.
-- ---------------------------------------------------------------------
CREATE VIEW vw_existencia_calculada AS
SELECT p.id_producto,
       p.codigo,
       p.nombre,
       p.stock_actual AS existencia_registrada,
       COALESCE(SUM(CASE WHEN m.tipo_movimiento = 'ENTRADA' THEN  m.cantidad
                         WHEN m.tipo_movimiento = 'SALIDA'  THEN -m.cantidad
                    END), 0)::INTEGER AS existencia_calculada,
       p.stock_actual - COALESCE(SUM(CASE WHEN m.tipo_movimiento = 'ENTRADA' THEN  m.cantidad
                                          WHEN m.tipo_movimiento = 'SALIDA'  THEN -m.cantidad
                                     END), 0)::INTEGER AS diferencia
FROM   producto p
LEFT   JOIN movimiento_inventario m ON m.id_producto = p.id_producto
GROUP  BY p.id_producto, p.codigo, p.nombre, p.stock_actual;


-- ---------------------------------------------------------------------
--  vw_valor_inventario
--  Valuacion del inventario a partir de las capas de costo vigentes.
-- ---------------------------------------------------------------------
CREATE VIEW vw_valor_inventario AS
SELECT p.id_producto,
       p.codigo,
       p.nombre,
       c.nombre AS categoria,
       p.stock_actual,
       COALESCE(SUM(ci.cantidad_disponible), 0)::INTEGER              AS unidades_en_capas,
       COALESCE(SUM(ci.cantidad_disponible * ci.costo_unitario), 0)   AS valor_total,
       CASE WHEN COALESCE(SUM(ci.cantidad_disponible), 0) > 0
            THEN ROUND(SUM(ci.cantidad_disponible * ci.costo_unitario)
                       / SUM(ci.cantidad_disponible), 4)
            ELSE 0
       END AS costo_promedio
FROM   producto  p
JOIN   categoria c  ON c.id_categoria = p.id_categoria
LEFT   JOIN capa_inventario ci ON ci.id_producto = p.id_producto
                              AND ci.cantidad_disponible > 0
GROUP  BY p.id_producto, p.codigo, p.nombre, c.nombre, p.stock_actual;


-- ---------------------------------------------------------------------
--  vw_kardex
--  Historial de movimientos legible, con el documento que origino cada
--  entrada o salida y el usuario responsable.
-- ---------------------------------------------------------------------
CREATE VIEW vw_kardex AS
SELECT m.id_movimiento,
       m.id_producto,
       p.codigo           AS codigo_producto,
       p.nombre           AS nombre_producto,
       m.fecha_movimiento,
       m.tipo_movimiento,
       m.origen,
       COALESCE(co.numero_documento, v.numero_factura) AS documento,
       COALESCE(pr.nombre, cl.nombre)                  AS tercero,
       m.cantidad,
       m.costo_unitario,
       (m.cantidad * m.costo_unitario) AS valor_movimiento,
       m.existencia_anterior,
       m.existencia_nueva,
       u.nombre_usuario   AS usuario,
       m.observaciones
FROM   movimiento_inventario m
JOIN   producto  p  ON p.id_producto  = m.id_producto
JOIN   usuario   u  ON u.id_usuario   = m.id_usuario
LEFT   JOIN compra    co ON co.id_compra    = m.id_compra
LEFT   JOIN proveedor pr ON pr.id_proveedor = co.id_proveedor
LEFT   JOIN venta     v  ON v.id_venta      = m.id_venta
LEFT   JOIN cliente   cl ON cl.id_cliente   = v.id_cliente;
